version: 2.1
jobs:
  setup:
      working_directory: ~/practice_circleci
      docker:
        - image : circleci/python:3.9
      steps:
        - checkout
        - run:
            name: installing python dependencies
            command: |
              echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV  && source $BASH_ENV
              pip install --user -r requirements.txt
  execute:
      working_directory: ~/practice_circleci
      docker:
        - image: circleci/python:3.9
      steps:
        - run:
            name: run unit test
            command: |
              python testrestapi.py

workflows:
  install_and_run:
    jobs:
      - setup
      - execute:
          - requires:
             - setup



